### ISSUE TITLE
What is the license on BLExplorer

### ISSUE THREAD

**Issue by andyparkins** [ligi/BLExplorer#6]
I've made some small patches to BLExplorer, mostly to help with testing our own BLE beacon internally.

However, a customer recently asked for an example of how to read data from our beacons and I was about to hand over the source to BLExplorer with my own patches on top when I realised I don't know what the license is.

Could you make it explicit somewhere in the source tree what your preferences are.  Being on github, I assume it's open source, but I'd like to be sure we're not misusing what you've kindly shared by pointing customers at it.

(I should be clear, we have no wish to rebadge or resell or whatever, it's purely a source-included example for customers who want to write their own BLE applications)

**Comment by ligi** [comment]
Oh - you are completely correct - sorry for this. I would add a GPLv3 license if this is OK for you. Should have been done in the beginning - not sure why this slipped. It is mentioned on fdroid: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.ligi.blexplorer.txt#L2 
Hope GPLv3 works for you

**Comment by andyparkins** [comment]
That's absolutely fine; I certainly wasn't asking for any particularly license -- just to know what license it is.

GPLv3 is perfect.  I want to give source out anyway, so GPLv3 is not a problem; and I like it as a default anyway :-)

Thanks for getting back to me so quickly.
